name: repo-add for Archlinux
description: repo-add for Archlinux
inputs:
  name:
    description: Repo Name
    required: false
    default: 'aur'
  token:
    description: GitHub Token
    required: true
  packager:
    description: Packager Name and Email
    required: false
    default: 'GitHub Action <github-action@users.noreply.github.com>'
  gpgkey:
    description: gpg key
    required: false
    default: 'key.gpg.enc'
  secret:
    description: secret key to dencrypt gpg key
    required: true
outputs:
  removed:
    description: "Removed Packages"
    value: ${{ steps.repo.outputs.removed }}
runs:
  using: composite
  steps:
    - name: Get current version
      continue-on-error: true
      uses: robinraju/release-downloader@v1.4
      with:
        latest: true
        fileName: ${{ inputs.name }}*
        tarBall: false
        zipBall: false
        token: ${{ inputs.token }}
    - uses: actions/download-artifact@v3
      with:
        name: packages
        path: pkg/

    - id: repo
      name: "Create Repo"
      uses: ./.github/actions/archlinux
      with:
        packager: ${{ inputs.packager }}
        script: repo-add
        args: ${{ inputs.name }}
    - name: "Cleanup old files"
      run: rm -f *.old *.old.sig
      shell: bash
    - name: "Sign Repo"
      uses: ./.github/actions/sign
      with:
        secret: ${{ inputs.secret }}
        gpgkey: ${{ inputs.gpgkey }}
        file: '${{ inputs.name }}.db'
    - uses: actions/upload-artifact@v3
      with:
        name: packages
        path: ${{ inputs.name }}*
        retention-days: 1