name: Makepkg for Archlinux
description: Makepkg for Archlinux
inputs:
  package:
    description: package
    required: true
  token:
    description: GitHub Token
    required: true
  packager:
    description: Packager Name and Email
    required: false
    default: 'GitHub Action <github-action@users.noreply.github.com>'
  gpgkey:
    description: gpg key
    required: false
    default: 'key.gpg.enc'
  secret:
    description: secret key to dencrypt gpg key
    required: true
runs:
  using: composite
  steps:
    - name: Get current version ${{ inputs.package }}
      continue-on-error: true
      uses: robinraju/release-downloader@v1.4
      with:
        latest: true
        fileName: ${{ inputs.package }}*
        tarBall: false
        zipBall: false
        token: ${{ inputs.token }}
    - name: Build Package ${{ inputs.package }}
      uses: ./.github/actions/archlinux
      with:
        packager: ${{ inputs.packager }}
        directory: ${{ inputs.package }}
        scripts: makepkg -si -C -c --noconfirm --noprogressbar
    - name: "Sign Package"
      uses: ./.github/actions/sign
      with:
        secret: ${{ inputs.secret }}
        gpgkey: ${{ inputs.gpgkey }}
        file: '${{ inputs.package }}\*.pkg.tar.zst'
    - uses: actions/upload-artifact@v3
      with:
        name: packages
        path: ${{ inputs.package }}*.pkg.*
        retention-days: 1