name: Run Command In Archlinux Docker Container
description: Run Command In Archlinux Docker Container
inputs:
  directory:
    description: Directory to run from
    required: false
    default: '.'
  packager:
    description: Packager Name and Email
    required: false
    default: 'GitHub Action <github-action@users.noreply.github.com>'
  pkgdir:
    description: makepkg out directory
    required: false
    default: 'pkg'
  scripts:
    description: Script to run
    required: true
runs:
  using: docker
  image: Dockerfile
  env:
    PKGDEST: ${{inputs.pkgdir}}
    PACKAGER: ${{inputs.packager}}
  args:
    - ${{inputs.directory}}
    - "${{inputs.scripts}}"