on:
  push:
    branches:
      - master

jobs:
  variables:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - id: set-matrix
      run: echo "::set-output name=matrix::`find . -iname 'PKGBUILD' -exec bash -c \"basename \\$(dirname \\"{}\\")\" \; | jq -R -s -c 'split(\"\n\")[:-1]'`"

  build-packages:
    runs-on: ubuntu-latest
    needs: variables

    strategy:
      matrix:
        package: ${{fromJson(needs.variables.outputs.matrix)}}
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build ${{ matrix.package }}
      uses: ./.github/actions/makepkg
      continue-on-error: true
      with:
        package: ${{ matrix.package }}
        token: ${{ secrets.GITHUB_TOKEN }}
        packager: "James C Kimble (Github Actions) <me@jckimble.com>"
        secret: ${{ secrets.ENCRYPTION_KEY }}
  
  build-repo:
    runs-on: "ubuntu-latest"
    needs: build-packages

    steps:
    - uses: actions/checkout@v3
    - name: Get current version
      continue-on-error: true
      uses: robinraju/release-downloader@v1.4
      with:
        latest: true
        fileName: jckimble.db.tar.xz
        tarBall: false
        zipBall: false
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/download-artifact@v3
      with:
        name: packages
        path: pkg/
    - name: "Create Repo"
      uses: ./.github/actions/archlinux
      with:
        packager: "James C Kimble (Github Actions) <me@jckimble.com>"
        scripts: "repo-add -q jckimble.db.tar.xz pkg/*.pkg.tar.zst"
    - name: "Cleanup old files"
      run: rm -f *.old
    - name: "Sign Repo"
      uses: ./.github/actions/sign
      with:
        secret: ${{ secrets.ENCRYPTION_KEY }}
        gpgkey: "key.gpg.enc"
        file: 'jckimble.db.tar.xz'
    - name: "Upload Packages"
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: repository
        file: 'pkg/*'
        file_glob: true
        overwrite: true
    - name: "Upload Database"
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: repository
        file: jckimble*
        file_glob: true
        overwrite: true
